{% set name = "edgetest" %}
{% set version = "2021.12.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7398df58b53e65e7f9d2779972087e9eef907c2d020669a3762253ddf5b61725

build:
  noarch: python
  entry_points:
    - edgetest=edgetest.interface:cli
  number: 0
  script: "{{ PYTHON }} -m pip install -vv --no-deps --ignore-installed ."

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - Cerberus >=1.3.0,<=1.3.4
    - click >=7.0,<=8.0.3
    - pluggy <=1.0.0,>=1.0.0
    - tabulate >=0.8.9,<=0.8.9
    - packaging >20.6,<=21.3
    - python >=3.7

test:
  imports:
    - edgetest

about:
  home: https://github.com/capitalone/edgetest
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'edgetest is a tox-inspired python library that tests your package against the latest available dependency versions.'
  description: |
    edgetest is a tox-inspired python library that tests your package against the latest available dependency versions.
    It will create a virtual environment, install your local package into the environment, upgrade specified dependency
    package(s), and run your test command.
  doc_url: https://capitalone.github.io/edgetest/
  dev_url: https://github.com/capitalone/edgetest

extra:
  recipe-maintainers:
    - fdosani
    - ak-gupta
